# Generated by Django 3.2.3 on 2022-04-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('vote_avg', models.FloatField()),
                ('genre', models.CharField(max_length=255)),
                ('movie_img_url', models.URLField()),
                ('release_date', models.DateTimeField()),
            ],
        ),
    ]
